version: '3.7'
services:
 mysql:
  container_name: ${NAME}_mysql
  image: mysql:8.0.13
  restart: on-failure
  command: ["--default-authentication-plugin=mysql_native_password"]
  volumes:
   - "./.data/mysql:/var/lib/mysql"
  environment:
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_DATABASE_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  networks:
   default:
    ipv4_address: ${MYSQL_IP}
 php:
  container_name: ${NAME}_php
  build:
   context: ./etc/php
  volumes:
   - "./project/:/srv/src/project:cached"
   - "./etc/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
  networks:
   default:
    ipv4_address: ${PHP_IP}
  environment:
   PHP_IDE_CONFIG: "serverName=planner.loc"
  extra_hosts:
   - "host.docker.internal:host-gateway"
 nginx:
  container_name: ${NAME}_nginx
  image: nginx:1.15.8
  volumes:
   - "./.data/nginx/logs:/var/log/nginx"
   - "./etc/nginx/project.conf:/etc/nginx/conf.d/default.conf"
   - "./project/:/srv/src/project:cached"
  networks:
   default:
    ipv4_address: ${NGINX_IP}
networks:
 default:
  driver: bridge
  ipam:
   driver: default
   config:
    - subnet: ${SUBNET}

